<?php
return [
  [
    'date_add' => '2015-10-23 22:36:38',
    'username' => 'Administrator',
    'auth_key' => 'VPfQqzCYA1vsSYBALa-W89xKWs0qP-Cv',
    'email_confirm_token' => null,
    'password_hash' => '$2y$13$kbYbZ6Isko0Krw5zoFCxie3ck8ItxROkG1iqtoLnu89Ok0IXyXqiu',
    'password_reset_token' => null,
    'email' => 'mail@gmail.com',
    'root' => 1,
    'banned' => 0,
  ],
  [
    'date_add' => '2015-10-23 22:36:38',
    'username' => 'Administrator',
    'auth_key' => 'VPfQqzCYA1vsSYBALa-W89xKWs0qP-Cv',
    'email_confirm_token' => null,
    'password_hash' => '$2y$13$kbYbZ6Isko0Krw5zoFCxie3ck8ItxROkG1iqtoLnu89Ok0IXyXqiu',
    'password_reset_token' => null,
    'email' => 'bannedAdmin@gmail.com',
    'root' => 1,
    'banned' => 1,
  ],
  [
    'date_add' => '2015-10-23 22:37:37',
    'username' => 'John Doe',
    'auth_key' => 'RljhOkjTa6-ylbsYCS2UIPp-LN5pRAQY',
    'email_confirm_token' => null,
    'password_hash' => '$2y$13$Wb.CqmAbDkpgS1wRegnYS.KAIZQ0bhaCHkciO3YUGERyiZ28AP5Fe',
    'password_reset_token' => null,
    'email' => 'johndoe@gmail.com',
    'root' => 0,
    'banned' => 0,
  ],
];
