services:
    nginx:
        image: nginx:latest
        ports:
            - "8090:8080"
            - "8091:8081"
        volumes:
            - ./app:/var/www/app
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/app
        networks:
            - backend
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php/php-fpm.docker
        environment:
            APP_ENV: dev
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        networks:
            - backend
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql57
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "yii2db"
        networks:
            - backend
        ports:
            - "3306:3306"

networks:
    backend:
        driver: bridge