version: '3'
services:
    php-apache:
        build:
            context: ./apache
            dockerfile: Dockerfile
        container_name: php74
        volumes:
            - ./app:/var/www/html
        ports:
            - 8080:8080
            - 8081:8081
        networks:
            - backend
    mysql:
        image: mysql:5.7
        container_name: mysql57
        restart: always
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
        networks:
            - backend
        ports:
            - 3306:3306

networks:
    backend:
        driver: bridge