-- ----------------------------
-- Records of regions
-- ----------------------------
INSERT INTO `region` VALUES ('1', 'Томская область');
INSERT INTO `region` VALUES ('2', 'Республики Хакасия');
INSERT INTO `region` VALUES ('3', 'Республика Татарстан');
INSERT INTO `region` VALUES ('4', 'Краснодарский край');
INSERT INTO `region` VALUES ('5', 'Иркутская область');
INSERT INTO `region` VALUES ('6', 'Нижегородская область');
INSERT INTO `region` VALUES ('7', 'Приморский край');
INSERT INTO `region` VALUES ('8', 'Архангельская область');
INSERT INTO `region` VALUES ('9', 'Астраханская область');
INSERT INTO `region` VALUES ('10', 'Красноярский край');
INSERT INTO `region` VALUES ('11', 'Саратовская область');
INSERT INTO `region` VALUES ('12', 'Московская область');
INSERT INTO `region` VALUES ('13', 'Алтайский край');
INSERT INTO `region` VALUES ('14', 'Ростовская область');
INSERT INTO `region` VALUES ('15', 'Белгородская область');
INSERT INTO `region` VALUES ('16', 'Республика Карелия');
INSERT INTO `region` VALUES ('17', 'Новосибирская область');
INSERT INTO `region` VALUES ('18', 'Пермский край');
INSERT INTO `region` VALUES ('19', 'Еврейская автономная область');
INSERT INTO `region` VALUES ('20', 'Амурская область');
INSERT INTO `region` VALUES ('21', 'Брянская область');
INSERT INTO `region` VALUES ('22', 'Псковская область');
INSERT INTO `region` VALUES ('23', 'Новгородская область');
INSERT INTO `region` VALUES ('24', 'Северная Осетия');
INSERT INTO `region` VALUES ('25', 'Владимирская область');
INSERT INTO `region` VALUES ('26', 'Волгоградская область');
INSERT INTO `region` VALUES ('27', 'Вологодская область');
INSERT INTO `region` VALUES ('28', 'Республика Коми');
INSERT INTO `region` VALUES ('29', 'Воронежская область');
INSERT INTO `region` VALUES ('30', 'Удмуртия');
INSERT INTO `region` VALUES ('31', 'Чечня');
INSERT INTO `region` VALUES ('32', 'Дагестан');
INSERT INTO `region` VALUES ('33', 'Ульяновская область');
INSERT INTO `region` VALUES ('34', 'Республика Крым');
INSERT INTO `region` VALUES ('35', 'Свердловская область');
INSERT INTO `region` VALUES ('36', 'Липецкая область');
INSERT INTO `region` VALUES ('37', 'Ставропольский край');
INSERT INTO `region` VALUES ('38', 'Челябинская область');
INSERT INTO `region` VALUES ('39', 'Ивановская область');
INSERT INTO `region` VALUES ('40', 'Тюменская область');
INSERT INTO `region` VALUES ('41', 'Марий Эл');
INSERT INTO `region` VALUES ('42', 'Калининградская область');
INSERT INTO `region` VALUES ('43', 'Калужская область');
INSERT INTO `region` VALUES ('44', 'Кемеровская область');
INSERT INTO `region` VALUES ('45', 'Кировская область');
INSERT INTO `region` VALUES ('46', 'Ленинградская область');
INSERT INTO `region` VALUES ('47', 'Хабаровский край');
INSERT INTO `region` VALUES ('48', 'Костромская область');
INSERT INTO `region` VALUES ('49', 'Пензенская область');
INSERT INTO `region` VALUES ('50', 'Курганская область');
INSERT INTO `region` VALUES ('51', 'Курская область');
INSERT INTO `region` VALUES ('52', 'Тыва');
INSERT INTO `region` VALUES ('53', 'Магаданская область');
INSERT INTO `region` VALUES ('54', 'Адыгея');
INSERT INTO `region` VALUES ('55', 'Мурманская область');
INSERT INTO `region` VALUES ('56', 'Ингушетия');
INSERT INTO `region` VALUES ('57', 'Кабардино-Балкария');
INSERT INTO `region` VALUES ('58', 'Ненецкий автономный округ');
INSERT INTO `region` VALUES ('59', 'Башкортостан');
INSERT INTO `region` VALUES ('60', 'Ханты-Мансийский автономный округ');
INSERT INTO `region` VALUES ('61', 'Самарская область');
INSERT INTO `region` VALUES ('62', 'Тульская область');
INSERT INTO `region` VALUES ('63', 'Чувашия');
INSERT INTO `region` VALUES ('64', 'Ямало-Ненецкий ');
INSERT INTO `region` VALUES ('65', 'Омская область');
INSERT INTO `region` VALUES ('66', 'Орловская область');
INSERT INTO `region` VALUES ('67', 'Оренбургская область');
INSERT INTO `region` VALUES ('68', 'Ярославская область');
INSERT INTO `region` VALUES ('69', 'Рязанская область');
INSERT INTO `region` VALUES ('70', 'Мордовия');
INSERT INTO `region` VALUES ('71', 'Смоленская область');
INSERT INTO `region` VALUES ('72', 'Тамбовская область');
INSERT INTO `region` VALUES ('73', 'Тверская область');
INSERT INTO `region` VALUES ('74', 'Бурятия');
INSERT INTO `region` VALUES ('75', 'Забайкальский край');
INSERT INTO `region` VALUES ('76', 'Калмыкия');
INSERT INTO `region` VALUES ('77', 'Сахалинская область');
INSERT INTO `region` VALUES ('78', 'Якутия');
INSERT INTO `region` VALUES ('79', 'Севастополь');
